config/routes.rb
SevenPortfolio::Engine.routes.draw do
  resources :item_videos
  resources :items

  mount SevenGallery::Engine, at: "/"
end

app/models/seven_gallery/gallery.rb
class SevenGallery::Gallery < ActiveRecord::Base
  include SevenGallery::Concerns::Gallery
  belongs_to :item, :class_name => 'SevenPortfolio::Item'
end

app/models/seven_portfolio/concerns/item.rb
module SevenPortfolio::Concerns::Item
  extend ActiveSupport::Concern
  included do
    enum item_type: [:no_media, :gallery, :video]
    has_one :item_video, class_name:'SevenPortfolio::ItemVideo', foreign_key: "seven_portfolio_item_id"
    has_one :item_gallery, class_name: 'SevenGallery::Gallery', foreign_key: "seven_portfolio_item_id"
    accepts_nested_attributes_for :item_video, :item_gallery, reject_if: :no_media?

    before_save :set_gallery_name, if: :gallery?

  end

  def set_gallery_name
    build_item_gallery(title: "#{title}_gallery")
  end

  def type_content
    if no_media?
      nil
    elsif gallery?
      item_gallery
    elsif video?
      item_video
    end
  end


end

app/models/seven_portfolio/concerns/item_video.rb
module SevenPortfolio::Concerns::ItemVideo
  extend ActiveSupport::Concern

  included do
    belongs_to :item, class_name: 'SevenPortfolio::Item'
  end
end

app/models/seven_portfolio/item.rb
module SevenPortfolio
  class Item < ActiveRecord::Base
    include SevenPortfolio::Concerns::Item
  end
end

app/models/seven_portfolio/item_video.rb
module SevenPortfolio
  class ItemVideo < ActiveRecord::Base
    include SevenPortfolio::Concerns::ItemVideo
  end
end

app/controllers/seven_portfolio/application_controller.rb
module SevenPortfolio
  class ApplicationController < ActionController::Base
  end
end

app/controllers/seven_portfolio/concerns/item_videos_controller.rb
module SevenPortfolio::Concerns::ItemVideosController
  extend ActiveSupport::Concern

  included do
    before_action :set_item_video, only: [:show, :edit, :update, :destroy]
  end

  # GET /item_videos
  def index
    @item_videos = ItemVideo.all
  end

  # GET /item_videos/1
  def show
  end

  # GET /item_videos/new
  def new
    @item_video = ItemVideo.new
  end

  # GET /item_videos/1/edit
  def edit
  end

  # POST /item_videos
  def create
    @item_video = ItemVideo.new(item_video_params)

    if @item_video.save
      redirect_to @item_video, notice: 'Item video was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /item_videos/1
  def update
    if @item_video.update(item_video_params)
      redirect_to @item_video, notice: 'Item video was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /item_videos/1
  def destroy
    @item_video.destroy
    redirect_to item_videos_url, notice: 'Item video was successfully destroyed.'
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_item_video
    @item_video = ItemVideo.find(params[:id])
  end

  # Only allow a trusted parameter "white list" through.
  def item_video_params
    params[:item_video].permit(:url, :description, :title)
  end
end

app/controllers/seven_portfolio/concerns/items_controller.rb
module SevenPortfolio::Concerns::ItemsController
  extend ActiveSupport::Concern

  included do
    before_action :set_item, only: [:show, :edit, :update, :destroy]
  end
  # GET /items
  def index
    @items = SevenPortfolio::Item.all
  end

  # GET /items/1
  def show
    @photos = @item.item_gallery.photos.page(params[:page]) if @item.gallery?
  end

  # GET /items/new
  def new
    @item = SevenPortfolio::Item.new
    @item.build_item_video
    @item.build_item_gallery
  end

  # GET /items/1/edit
  def edit
  end

  # POST /items
  def create
    @item = SevenPortfolio::Item.new(item_params)
    if @item.save
      redirect_to @item, notice: 'Item was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /items/1
  def update
    if @item.update(item_params)
      redirect_to @item, notice: 'Item was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /items/1
  def destroy
    @item.destroy
    redirect_to items_url, notice: 'Item was successfully destroyed.'
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_item
    @item = SevenPortfolio::Item.find(params[:id])
    @item.item_video ||= SevenPortfolio::ItemVideo.new

  end

  # Only allow a trusted parameter "white list" through.
  def item_params
    params[:item].permit(:description, :finished_at, :is_featured, :item_type,
                         item_video_attributes: [:url, :description, :title],
                         item_gallery_attributes: [:title])
  end
end

app/controllers/seven_portfolio/item_videos_controller.rb
require_dependency "seven_portfolio/application_controller"

module SevenPortfolio
  class ItemVideosController < ApplicationController
    include SevenPortfolio::Concerns::ItemVideosController
  end
end

app/controllers/seven_portfolio/items_controller.rb
require_dependency "seven_portfolio/application_controller"

module SevenPortfolio
  class ItemsController < ApplicationController
    include SevenPortfolio::Concerns::ItemsController
  end
end

app/helpers/seven_portfolio/application_helper.rb
module SevenPortfolio
  module ApplicationHelper
  end
end

app/helpers/seven_portfolio/item_videos_helper.rb
module SevenPortfolio
  module ItemVideosHelper
  end
end

app/helpers/seven_portfolio/items_helper.rb
module SevenPortfolio
  module ItemsHelper
  end
end

app/views/layouts/seven_portfolio/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>SevenPortfolio</title>
  <%= stylesheet_link_tag    "seven_portfolio/application", media: "all" %>
  <%= javascript_include_tag "seven_portfolio/application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<div class="container"><%= yield %></div>

</body>
</html>

app/views/seven_portfolio/item_gallery/_fields.html.erb
<div class="field">
  <%= f.label :title %><br>
  <%= f.text_field :title %>
</div>

app/views/seven_portfolio/item_gallery/photos/_form.html.erb
<%= render "seven_portfolio/item_gallery/photos/uploader_wrapper" %>

<%= link_to "rearrange", seven_gallery.arrange_photos_gallery_path(@item.item_gallery) %>

<%= render "seven_portfolio/item_gallery/photos/photos_wrapper", photos: @item.item_gallery.photos %>
<div class="row">
  <%= paginate @photos %>
</div>

app/views/seven_portfolio/item_gallery/photos/_photos_wrapper.html.erb
<div class="row">
  <h3>Photos: </h3>

  <div>
    <% photos.each do |photo| %>
        <div id="photo_<%= photo.id %>">
          <%= photo.caption %> - <%= image_tag photo.image_url(:thumb) %>
          <%= link_to 'edit', seven_gallery.edit_gallery_photo_path(@item.item_gallery, photo) %> -
          <%= link_to 'delete', seven_gallery.gallery_photo_path(@item.item_gallery, photo), method: :delete, data: {confirm: 'Sure?'} %>
        </div>
    <% end %>
  </div>
</div>

app/views/seven_portfolio/item_gallery/photos/_uploader_wrapper.html.erb
<h4>upload:</h4>
<div id="uploaderWrapper" class="dropzone" data-name="photo[image]" data-url="<%= url_for seven_gallery.gallery_photos_url(@item.item_gallery) %>">
  <p class="dz-message">Select photos</p>
</div>

app/views/seven_portfolio/item_videos/_fields.html.erb
<div>
  <%= f.label :title %>
  <%= f.text_field :title %>
</div>
<div>
  <%= f.label :url %>
  <%= f.text_field :url %>
</div>
<div>
  <%= f.label :description %>
  <%= f.text_field :description %>
</div>

app/views/seven_portfolio/item_videos/_form.html.erb
<%= form_for(@item_video) do |f| %>
    <% if @item_video.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@item_video.errors.count, "error") %> prohibited this item_video from being saved:</h2>

          <ul>
            <% @item_video.errors.full_messages.each do |message| %>
                <li><%= message %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

    <%= render "seven_portfolio/item_videos/fields", f: f %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/seven_portfolio/item_videos/_show.html.erb
<p>url: <%= auto_html(@item.item_video.url) { youtube; vimeo; } %></p>
<p>title: <%= @item.item_video.title %></p>
<p>desc: <%= @item.item_video.description %></p>

app/views/seven_portfolio/item_videos/edit.html.erb
<h1>Editing Item Video</h1>

<%= render 'form' %>

<%= link_to 'Show', @item_video %> |
<%= link_to 'Back', item_videos_path %>

app/views/seven_portfolio/item_videos/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Item Videos</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @item_videos.each do |item_video| %>
      <tr>
        <td><%= link_to 'Show', item_video %></td>
        <td><%= link_to 'Edit', edit_item_video_path(item_video) %></td>
        <td><%= link_to 'Destroy', item_video, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Item video', new_item_video_path %>

app/views/seven_portfolio/item_videos/new.html.erb
<h1>New Item Video</h1>

<%= render 'form' %>

<%= link_to 'Back', item_videos_path %>

app/views/seven_portfolio/items/_form.html.erb
<%= form_for @item do |f| %>
    <% if @item.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@item.errors.count, "error") %> prohibited this item from being saved:</h2>

          <ul>
            <% @item.errors.full_messages.each do |message| %>
                <li><%= message %></li>
            <% end %>
          </ul>
        </div>
    <% end %>
    <div>
      <%= f.label :description %>
      <%= f.text_area :description %>
    </div>
    <div>
      <%= f.label :is_featured %>
      <%= f.check_box :is_featured %>
    </div>
    <div>
      <%= f.label :finished_at %>
      <%= f.date_select :finished_at %>
    </div>
    <div>
      <%= f.label :item_type %>
      <br/>

      <div class="item_type_radio_wrapper">
        <%= f.radio_button :item_type, :no_media, id: :item_type_no_media, class: :item_type_radio %>
        <%= f.label :item_type, "No Media", for: :item_type_no_media %>

        <%= f.radio_button :item_type, :gallery, id: :item_type_gallery, class: :item_type_radio %>
        <%= f.label :item_type, "Gallery", for: :item_type_gallery %>

        <%= f.radio_button :item_type, :video, id: :item_type_video, class: :item_type_radio %>
        <%= f.label :item_type, "Video", for: :item_type_video %>
      </div>
    </div>
    <div class="item_type_wrapper">
       <div class="item_video_wrapper" data-id="item_type_video">
        <%= f.fields_for :item_video do |f_v| %>
            <%= render "seven_portfolio/item_videos/fields", f: f_v %>
        <% end %>
      </div>
    </div>
    <div class="actions">
      <%= f.submit %>
    </div>
<% end %>

app/views/seven_portfolio/items/edit.html.erb
<h1>Editing Item</h1>

<%= render 'form' %>

<%= link_to 'Show', @item %> |
<%= link_to 'Back', items_path %>

app/views/seven_portfolio/items/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Items</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @items.each do |item| %>
      <tr>
        <td><%= item.description %></td>
        <td><%= link_to 'Show', item %></td>
        <td><%= link_to 'Edit', edit_item_path(item) %></td>
        <td><%= link_to 'Destroy', item, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Item', new_item_path %>

app/views/seven_portfolio/items/new.html.erb
<h1>New Item</h1>

<%= render 'form' %>

<%= link_to 'Back', items_path %>

app/views/seven_portfolio/items/show.html.erb
<p id="notice"><%= notice %></p>

<div><%= @item.description %></div>
<div><%= @item.is_featured %></div>
<div><%= @item.finished_at %></div>
<div><%= @item.item_type %></div>

<%= link_to 'Edit', edit_item_path(@item) %> |
<%= link_to 'Back', items_path %>

<% if @item.gallery? %>
    <%= render "seven_portfolio/item_gallery/photos/form" %>
<% elsif @item.video? %>
    <%= render "seven_portfolio/item_videos/show" %>
<% end %>